# Generated by Django 3.1.8 on 2021-05-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiliers',
            name='mob_img',
        ),
        migrations.AddField(
            model_name='mobiliers',
            name='mob_desc',
            field=models.CharField(default=2, max_length=900),
            preserve_default=False,
        ),
    ]
