# Generated by Django 3.1.8 on 2021-05-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touim', '0002_auto_20210511_0629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staticmap',
        ),
    ]
